/* eslint-env node */

export default {
  '*': (filenames) => {
    // Filter out CHANGELOG.md as it's auto-generated by semantic-release
    const filesToCheck = filenames.filter(
      (file) => !file.endsWith('CHANGELOG.md')
    )
    if (filesToCheck.length === 0) {
      return []
    }
    return `prettier --check ${filesToCheck.join(' ')}`
  }
}
